test_pool:
	g++ -std=c++14 -Wall -Wextra -Werror test_pool.cpp -o test_pool && ./test_pool; rm test_pool

test_buffer:
	g++ -std=c++14 -Wall -Wextra -Werror test_databuffer.cpp data_buffer.cpp -o test_databuffer && ./test_databuffer; rm test_databuffer